import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  ThumbsUp, Eye, ArrowLeft, Sparkles, Send, 
  MessageSquare, Share2, Check, BookOpen, Heart, RefreshCw 
} from 'lucide-react';
import { Article, Comment, ChatMessage } from '../types';

interface ArticleDetailProps {
  key?: React.Key | string;
  article: Article;
  onBack: () => void;
  onLike: (articleId: string) => void;
  onAddComment: (articleId: string, commentUser: string, commentText: string) => void;
  apiConfigured: boolean;
}

// Custom simple parser to safely convert Markdown-like bullets and bold generated by Gemini into clean JSX
function SimpleMarkdownRenderer({ text }: { text: string }) {
  if (!text) return null;

  const lines = text.split('\n');
  return (
    <div className="space-y-2 text-gray-700 leading-relaxed text-sm">
      {lines.map((line, index) => {
        const trimmed = line.trim();
        if (!trimmed) return <div key={index} className="h-2" />;

        // Handle Bullet Points
        if (trimmed.startsWith('•') || trimmed.startsWith('-') || trimmed.startsWith('*')) {
          const content = trimmed.substring(1).trim();
          return (
            <li key={index} className="list-none flex items-start gap-2 text-gray-700 pl-1">
              <span className="text-[#7E007E] font-bold mt-1">•</span>
              <span>{renderBoldText(content)}</span>
            </li>
          );
        }

        // Default Paragraph
        return <p key={index}>{renderBoldText(trimmed)}</p>;
      })}
    </div>
  );
}

function renderBoldText(rawText: string) {
  const parts = rawText.split('**');
  return parts.map((part, i) => {
    if (i % 2 === 1) {
      return <strong key={i} className="font-bold text-gray-900">{part}</strong>;
    }
    return part;
  });
}

export default function ArticleDetail({ 
  article, 
  onBack, 
  onLike, 
  onAddComment,
  apiConfigured
}: ArticleDetailProps) {
  const [commentUser, setCommentUser] = useState('');
  const [commentText, setCommentText] = useState('');
  const [isCopied, setIsCopied] = useState(false);
  
  // AI Summary State
  const [summary, setSummary] = useState<string>(article.aiSummary || '');
  const [isSummarizing, setIsSummarizing] = useState(false);
  const [summaryError, setSummaryError] = useState('');

  // AI Chat State
  const [chatInput, setChatInput] = useState('');
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([
    {
      id: 'welcome',
      role: 'model',
      text: `Halo! Saya Redaktur AI Tebarmedia. Ada bagian dari artikel "${article.title}" yang ingin Anda eksplorasi, pertanyakan, atau diskusikan lebih jauh? Silakan ketik di bawah!`,
      timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' })
    }
  ]);
  const [isChatting, setIsChatting] = useState(false);
  const [chatError, setChatError] = useState('');

  const chatEndRef = useRef<HTMLDivElement>(null);

  // Auto-scroll chat to bottom
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatMessages, isChatting]);

  const handleShareClick = () => {
    navigator.clipboard.writeText(window.location.href);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleAddCommentSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!commentUser.trim() || !commentText.trim()) return;

    onAddComment(article.id, commentUser, commentText);
    setCommentUser('');
    setCommentText('');
  };

  // Generate AI Summary calling the backend
  const generateAiSummary = async () => {
    if (isSummarizing) return;
    setIsSummarizing(true);
    setSummaryError('');

    try {
      const response = await fetch('/api/news/summarize', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          articleTitle: article.title,
          articleContent: article.content
        }),
      });

      const data = await response.json();
      if (response.ok) {
        setSummary(data.summary);
        // Persist summary cached onto article reference
        article.aiSummary = data.summary;
      } else {
        setSummaryError(data.error || 'Gagal merancang ringkasan berita.');
      }
    } catch (err: any) {
      setSummaryError('Masalah jaringan ke redaksi AI.');
    } finally {
      setIsSummarizing(false);
    }
  };

  // context chatbot logic with article reference
  const handleSendChat = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!chatInput.trim() || isChatting) return;

    const userMessage: ChatMessage = {
      id: `u-${Date.now()}`,
      role: 'user',
      text: chatInput,
      timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' })
    };

    setChatMessages((prev) => [...prev, userMessage]);
    setChatInput('');
    setIsChatting(true);
    setChatError('');

    const updatedHistory = [...chatMessages, userMessage];

    try {
      const response = await fetch('/api/news/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: updatedHistory.filter(m => m.id !== 'welcome'),
          articleTitle: article.title,
          articleContent: article.content
        }),
      });

      const data = await response.json();
      if (response.ok) {
        const modelMessage: ChatMessage = {
          id: `m-${Date.now() + 1}`,
          role: 'model',
          text: data.reply,
          timestamp: new Date().toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' })
        };
        setChatMessages(prev => [...prev, modelMessage]);
      } else {
        setChatError(data.error || 'Server gagal menanggapi obrolan.');
      }
    } catch (err: any) {
      setChatError('Koneksi terputus ke redaksi AI.');
    } finally {
      setIsChatting(false);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: 15 }}
      className="max-w-7xl mx-auto px-4 py-8"
      id="article-detail-view"
    >
      {/* Back CTA Row */}
      <button 
        id="btn-back-to-home"
        onClick={onBack}
        className="flex items-center gap-2 text-gray-500 hover:text-[#7E007E] font-medium transition-colors mb-6 cursor-pointer group"
      >
        <ArrowLeft className="w-5 h-5 transition-transform group-hover:-translate-x-1" />
        Kembali ke Beranda
      </button>

      {/* Main Grid: Left is article details & comments, Right is AI services */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start" id="detail-main-grid">
        
        {/* Left Column (8 units) */}
        <div className="lg:col-span-8 space-y-8" id="detail-left-column">
          
          {/* Article Header Metadata */}
          <div className="space-y-4" id="detail-header-card">
            <div className="flex items-center gap-2" id="detail-category-row">
              <span className="px-3 py-1 bg-[#2B2455]/10 text-[#2B2455] rounded-full text-xs font-bold uppercase tracking-wider">
                {article.category}
              </span>
              {article.isAiGenerated && (
                <span className="flex items-center gap-1 px-3 py-1 bg-gradient-to-r from-[#7E007E] to-[#2B2455] text-white rounded-full text-xs font-semibold shadow-xs">
                  <Sparkles className="w-3.5 h-3.5 animate-pulse" />
                  Jurnalisme AI Tebar
                </span>
              )}
            </div>

            <h1 className="text-2xl sm:text-3xl md:text-4xl font-sans font-extrabold text-gray-950 tracking-tight leading-tight" id="detail-title">
              {article.title}
            </h1>

            {/* Author card & Actions */}
            <div className="flex flex-wrap items-center justify-between gap-4 py-4 border-y border-gray-100" id="detail-author-row">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-gradient-to-tr from-[#7E007E] to-[#2B2455] text-white font-bold flex items-center justify-center font-sans tracking-wider text-sm uppercase">
                  {article.author.split(' ').map(w => w[0]).join('').substring(0, 2)}
                </div>
                <div>
                  <div className="text-gray-900 font-bold text-sm">{article.author}</div>
                  <div className="text-xs text-gray-400 font-mono flex items-center gap-2">
                    <span>{article.publishedAt}</span>
                    <span>•</span>
                    <span className="flex items-center gap-1">
                      <BookOpen className="w-3 h-3" />
                      {article.readTime} Baca
                    </span>
                  </div>
                </div>
              </div>

              {/* Share & Like actions */}
              <div className="flex items-center gap-2" id="detail-actions-row">
                <button 
                  id="btn-like-article"
                  onClick={() => onLike(article.id)}
                  className="flex items-center gap-2 px-4 py-2 rounded-xl bg-rose-50 text-rose-600 hover:bg-rose-100 transition-colors text-sm font-semibold cursor-pointer active:scale-95"
                >
                  <Heart className="w-4.5 h-4.5 fill-rose-600" />
                  Suka ({article.likes})
                </button>
                <button 
                  id="btn-share-article"
                  onClick={handleShareClick}
                  className="flex items-center gap-2 px-4 py-2 rounded-xl bg-gray-50 text-gray-600 hover:bg-gray-100 transition-colors text-sm font-semibold cursor-pointer active:scale-95"
                >
                  {isCopied ? (
                    <>
                      <Check className="w-4.5 h-4.5 text-emerald-600" />
                      Tersalin!
                    </>
                  ) : (
                    <>
                      <Share2 className="w-4.5 h-4.5" />
                      Bagikan
                    </>
                  )}
                </button>
              </div>
            </div>
          </div>

          {/* Article Large Banner Image */}
          <div className="rounded-2xl overflow-hidden aspect-video bg-gray-50 shadow-xs border border-gray-100" id="detail-image-box">
            <img 
              src={article.imageUrl} 
              alt={article.title} 
              referrerPolicy="no-referrer"
              className="w-full h-full object-cover"
              onError={(e) => {
                e.currentTarget.src = `https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&q=80&w=1200`;
              }}
            />
          </div>

          {/* Article Main Text Content */}
          <div className="font-serif text-[#2B2455] text-lg leading-relaxed space-y-6 max-w-none prose prose-purple border-b border-gray-100 pb-8" id="detail-text-body">
            {article.content.split('\n\n').map((paragraph, idx) => (
              <p key={idx} className="whitespace-pre-wrap select-text selection:bg-[#7E007E]/20">
                {paragraph}
              </p>
            ))}
          </div>

          {/* Core Comments Section */}
          <div className="space-y-6" id="detail-comments-section">
            <h3 className="font-sans font-bold text-gray-900 text-xl flex items-center gap-2">
              <MessageSquare className="w-5.5 h-5.5 text-gray-500" />
              Kolom Komentar ({article.comments.length})
            </h3>

            {/* Comment Form */}
            <form onSubmit={handleAddCommentSubmit} className="bg-gray-50 border border-gray-100 p-5 rounded-2xl space-y-4" id="comment-form">
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <input 
                  type="text" 
                  placeholder="Nama Lengkap Anda"
                  value={commentUser}
                  onChange={(e) => setCommentUser(e.target.value)}
                  className="sm:col-span-1 px-4 py-2 rounded-xl border border-gray-200 bg-white text-sm focus:outline-none focus:ring-2 focus:ring-[#7E007E]/30 focus:border-[#7E007E] text-gray-800"
                  required
                  id="input-comment-user"
                />
                <span className="hidden sm:inline text-xs text-gray-400 self-center">Suara Anda berkontribusi pada informasi yang merata.</span>
              </div>
              <div className="relative">
                <textarea 
                  placeholder="Tuliskan gagasan, kritik, atau respon kritis Anda mengenai berita ini..."
                  value={commentText}
                  onChange={(e) => setCommentText(e.target.value)}
                  rows={3}
                  className="w-full px-4 py-3 rounded-xl border border-gray-200 bg-white text-sm focus:outline-none focus:ring-2 focus:ring-[#7E007E]/30 focus:border-[#7E007E] text-gray-800 resize-none"
                  required
                  id="input-comment-text"
                />
              </div>
              <button 
                type="submit"
                id="btn-submit-comment"
                className="px-5 py-2.5 rounded-xl bg-[#2B2455] hover:bg-[#1a1538] text-white text-xs font-bold flex items-center gap-2 cursor-pointer transition-colors"
              >
                Kirim Komentar Resmi
              </button>
            </form>

            {/* Comment Feed */}
            <div className="space-y-4" id="detail-comment-feed">
              {article.comments.length === 0 ? (
                <p className="text-gray-400 text-sm text-center py-6">Belum ada komentar resmi. Jadilah suara pertama yang memberikan respon bermanfaat!</p>
              ) : (
                article.comments.map((comment) => (
                  <div key={comment.id} className="flex gap-3 bg-white p-4 border border-gray-100 rounded-xl hover:border-gray-200 transition-colors" id={`comment-card-${comment.id}`}>
                    <div className="w-9 h-9 rounded-full bg-[#2B2455]/10 text-[#2B2455] flex items-center justify-center font-sans font-bold text-xs">
                      {comment.avatar}
                    </div>
                    <div>
                      <div className="flex items-center gap-2" id={`comment-meta-${comment.id}`}>
                        <span className="font-bold text-gray-900 text-sm">{comment.user}</span>
                        <span className="text-[10px] text-gray-400 font-mono">{comment.timestamp}</span>
                      </div>
                      <p className="text-gray-600 text-sm mt-1 whitespace-pre-wrap leading-relaxed">{comment.content}</p>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>

        {/* Right Column: AI Services widget (4 units) */}
        <div className="lg:col-span-4 space-y-6 lg:sticky lg:top-24" id="detail-right-column">
          
          {/* Widget 1: AI Summary Box */}
          <div className="bg-gradient-to-br from-indigo-50/60 to-purple-50/40 border border-purple-100 rounded-2xl p-5 shadow-xs relative overflow-hidden" id="ai-summary-widget">
            <div className="absolute top-0 right-0 w-32 h-32 bg-purple-200/10 rounded-full blur-2xl" />
            
            <div className="flex items-center justify-between mb-3" id="summary-header">
              <h3 className="font-sans font-bold text-gray-900 text-sm flex items-center gap-2 tracking-tight">
                <Sparkles className="w-4.5 h-4.5 text-[#7E007E] animate-pulse" />
                RINGKASAN ASISTEN AI
              </h3>
              {!apiConfigured && (
                <span className="px-2 py-0.5 bg-amber-100 text-amber-800 rounded text-[9px] font-bold uppercase">Mode Simulasi</span>
              )}
            </div>

            {summary ? (
              <div className="space-y-4" id="summary-has-content">
                <div className="bg-white/80 backdrop-blur-xs p-4 rounded-xl border border-purple-100 shadow-3xs" id="summary-content-box">
                  <SimpleMarkdownRenderer text={summary} />
                </div>
                <button 
                  onClick={generateAiSummary}
                  disabled={isSummarizing}
                  id="btn-re-summarize"
                  className="flex items-center justify-center gap-2 w-full px-3 py-2 text-xs font-bold border border-[#7E007E]/30 text-[#7E007E] hover:bg-[#7E007E]/5 rounded-xl transition-colors cursor-pointer disabled:opacity-50"
                >
                  <RefreshCw className={`w-3.5 h-3.5 ${isSummarizing ? 'animate-spin' : ''}`} />
                  Perbarui Ringkasan AI
                </button>
              </div>
            ) : (
              <div className="text-center py-6 space-y-4" id="summary-placeholder">
                <p className="text-gray-500 text-xs leading-relaxed px-2">Malas membaca naskah panjang? Biarkan asisten AI dari dapur redaksi Tebarmedia merangkum topik-topik krusial di atas untuk Anda.</p>
                <button 
                  onClick={generateAiSummary}
                  disabled={isSummarizing}
                  id="btn-trigger-ai-summary"
                  className="inline-flex items-center justify-center gap-2 px-5 py-2.5 bg-gradient-to-r from-[#7E007E] to-[#2B2455] hover:opacity-95 text-white rounded-xl text-xs font-bold shadow-sm transition-all focus:ring-2 focus:ring-[#7E007E]/30 cursor-pointer disabled:opacity-75"
                >
                  {isSummarizing ? (
                    <>
                      <LoaderIcon className="w-3.5 h-3.5 animate-spin" />
                      Meringkas Berita...
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-3.5 h-3.5" />
                      Buat Ringkasan Berita (AI)
                    </>
                  )}
                </button>
                {summaryError && <p className="text-xs text-rose-500 font-mono mt-2">{summaryError}</p>}
              </div>
            )}
          </div>

          {/* Widget 2: Dedicated context chat with Redaktur AI */}
          <div className="bg-white border border-gray-100 rounded-2xl shadow-xs overflow-hidden flex flex-col h-[450px]" id="ai-chat-widget">
            {/* Chat header */}
            <div className="bg-gradient-to-r from-[#2B2455] to-[#40367c] p-4 text-white flex items-center justify-between flex-shrink-0" id="chat-header">
              <div className="flex items-center gap-2.5">
                <div className="w-8.5 h-8.5 rounded-full bg-white/20 flex items-center justify-center">
                  <Sparkles className="w-4 h-4 text-purple-200" />
                </div>
                <div>
                  <div className="text-xs font-bold tracking-wider text-purple-200">REDAKSI ONLINE</div>
                  <div className="text-xs font-bold leading-tight">Tanya Redaktur AI Tebar</div>
                </div>
              </div>
              <div className="flex items-center gap-1.5" id="chat-connection-badge">
                <span className="w-2.5 h-2.5 bg-emerald-400 rounded-full animate-ping" />
                <span className="text-[10px] font-bold text-emerald-300">ONLINE</span>
              </div>
            </div>

            {/* Chat Messages */}
            <div className="flex-grow p-4 overflow-y-auto space-y-3 bg-gray-50/50" id="chat-messages-container">
              {chatMessages.map((msg) => {
                const isUser = msg.role === 'user';
                return (
                  <div 
                    key={msg.id} 
                    className={`flex ${isUser ? 'justify-end' : 'justify-start'}`}
                    id={`chat-bubble-${msg.id}`}
                  >
                    <div className={`max-w-[85%] rounded-2xl p-3 text-xs shadow-3xs leading-relaxed ${
                      isUser 
                        ? 'bg-[#2B2455] text-white rounded-br-3xs' 
                        : 'bg-white text-gray-800 border border-gray-100 rounded-bl-3xs'
                    }`}>
                      <div className="font-sans select-text">{msg.text}</div>
                      <div className={`text-[9px] font-mono mt-1 text-right ${isUser ? 'text-gray-300' : 'text-gray-400'}`}>
                        {msg.timestamp}
                      </div>
                    </div>
                  </div>
                );
              })}
              {isChatting && (
                <div className="flex justify-start animate-pulse" id="chat-loader">
                  <div className="bg-white border border-gray-100 rounded-2xl rounded-bl-3xs p-3 text-xs text-gray-500 flex items-center gap-2">
                    <div className="flex gap-1">
                      <span className="w-1.5 h-1.5 bg-[#7E007E] rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                      <span className="w-1.5 h-1.5 bg-[#7E007E] rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                      <span className="w-1.5 h-1.5 bg-[#7E007E] rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                    </div>
                    <span>Redaktur AI sedang berkontemplasi...</span>
                  </div>
                </div>
              )}
              {chatError && (
                <div className="bg-red-50 text-red-700 text-xs p-3 rounded-lg border border-red-100 font-mono text-center">
                  Error: {chatError}
                </div>
              )}
              <div ref={chatEndRef} />
            </div>

            {/* Chat Input form */}
            <form onSubmit={handleSendChat} className="p-3 border-t border-gray-100 bg-white flex gap-2 flex-shrink-0" id="chat-input-form">
              <input 
                type="text" 
                placeholder="Tanyakan klaim berita, tokoh, dll..."
                value={chatInput}
                onChange={(e) => setChatInput(e.target.value)}
                disabled={isChatting}
                className="flex-grow px-3.5 py-2.5 rounded-xl border border-gray-200 text-xs focus:outline-none focus:ring-2 focus:ring-[#7E007E]/20 focus:border-[#7E007E] text-gray-800"
                id="chat-text-input"
              />
              <button 
                type="submit"
                id="btn-send-chat"
                disabled={!chatInput.trim() || isChatting}
                className="p-2.5 rounded-xl bg-[#2B2455] hover:bg-[#1a1538] text-white disabled:opacity-50 flex items-center justify-center cursor-pointer active:scale-95 transition-transform"
              >
                <Send className="w-4 h-4" />
              </button>
            </form>
          </div>

        </div>

      </div>
    </motion.div>
  );
}

// Mini sub-loader component
function LoaderIcon({ className = "" }: { className?: string }) {
  return (
    <svg className={className} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
    </svg>
  );
}
